//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//
//

import AWSCore


// Name of OrderFlowers bot
let OrderFlowersBotName = "OncoBot"//"OrderFlowers"
// Alias for OrderFlowers bot
let OrderFlowersBotAlias = "$LATEST"
// Region for OrderFlowers bot
let OrderFlowersBotRegion: AWSRegionType = .USEast1
